services:
  backend:
    build:
      context: ./backend
    container_name: jobboardx-backend
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - jobs-db-data:/app/db
    networks:
      - jobboardx-net

  frontend:
    build:
      context: ./frontend
    container_name: jobboardx-frontend
    ports:
      - "${PORT}:3000"
    volumes:
      - ./frontend:/app
    env_file:
        - .env
    stdin_open: true
    tty: true
    networks:
      - jobboardx-ne

volumes:
  jobs-db-data:

networks:
  jobboardx-net:
    external: true
