kind: Service
apiVersion: v1
metadata:
  name: jobboardx-backend-service
  namespace: jobboardx-ns
spec:
  selector:
    app: jobboardx-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
