kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
metadata:
  name: jobboardx-backend-vpa
  namespace: jobboardx-ns
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jobboardx-backend-green
  updatePolicy:
    updateMode: "Auto"
